problem:
  arg:
    contest: "1676"
    problem: d
    class: contest
    group: ""
  inputStream: standard input
  memoryLimit: 256 megabytes
  name: D. X-Sum
  outputStream: standard output
  test:
    input:
    - tests/0.in
    output:
    - tests/0.out
  timeLimit: 2 seconds
