problem:
  arg:
    contest: "1676"
    problem: h1
    class: contest
    group: ""
  inputStream: standard input
  memoryLimit: 256 megabytes
  name: H1. Maximum Crossings (Easy Version)
  outputStream: standard output
  test:
    input:
    - tests/0.in
    output:
    - tests/0.out
  timeLimit: 1 second
