problem:
  arg:
    contest: "1676"
    problem: e
    class: contest
    group: ""
  inputStream: standard input
  memoryLimit: 256 megabytes
  name: E. Eating Queries
  outputStream: standard output
  test:
    input:
    - tests/0.in
    output:
    - tests/0.out
  timeLimit: 3.5 seconds
